## DEFAULTS
# API Settings
spring.application.name=NetworkCloudDrive
server.port=8080
environment.unit-test=false
# Security
use-http-basic-authentication=false
disable-csrf-protection=false
# CORS Example
#cors-allowed-origins-patterns="http://localhost:3000","http://192.168.1.*:3000","http://localhost:5173","http://192.168.1.*:5173"
#cors-allowed-headers="Origin","Content-Type","Accept","responseType","Authorization"
#cors-allowed-methods="GET","POST","PUT","OPTIONS","DELETE"
#cors-exposed-headers="Content-Disposition","Content-Length"
#cors-allow-credentials=true
#cors-maximum-age=3600
# Logging
logging.file.path=logs
debug=true
# SQLite Settings
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
# Upload limits (Example)
#Max size of single file upload
spring.servlet.multipart.max-file-size=500MB
#Max total size of the request
spring.servlet.multipart.max-request-size=500MB
#Max amount of files
server.tomcat.max-part-count=100